[package]
name = "keycloak-openapi-transformer"
version = "0.1.0"
authors = ["Chris Couzens <ccouzens@gmail.com>"]
edition = "2018"

[dependencies]
scraper = "0.10.0"
openapiv3 = "0.2.0"
serde = "1.0.90"
serde_json = "1.0"
